name: Publish Website

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Website Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create destination folders
        run: |
          mkdir files
          mkdir files/pages
          mkdir files/css
          mkdir files/img
          mkdir files/js
      - name: Copy HTML files
        run: cp -a ./pages ./files/ && cp ./index.html ./files/
      - name: Copy JS files
        run: cp -a ./js ./files
      - name: Copy CSS files
        run: cp -a ./css ./files/
      - name: Copy images
        run: cp -a ./img ./files/
      - name: Upload Website Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./files"
  setup:
    name: Setup GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v5
  deploy:
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [build, setup]
    steps:
      - name: Upload website files
        id: deployment
        uses: actions/deploy-pages@v4
    